apache_listen_port: 8084
apache_create_vhosts: no
apache_remove_default_vhost: yes
apache_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi
apache_mods_enabled:
  - wsgi.load
varnish_listen_port: 6081
varnish_default_backend_host: "web0"
varnish_default_backend_port: "{{ apache_listen_port }}"
solr_workspace: /home/beachmaster
solr_version: "3.6.2"
solr_host: "0.0.0.0"
localwiki_webapp_dir: "/srv/localwiki"
localwiki_webapp_git_repo: "https://github.com/lowiki-org/localwiki-backend-server.git"
localwiki_webapp_git_checkout: "origin/production"
public_hostname: "lowiki.org"
custom_domains:
  - lowiki.tw
private_ips:
  bal0: '192.168.156.39'
  cache0: '192.168.136.236'
  db0: '192.168.145.251'
  web0: '192.168.158.216'
  web1: '192.168.139.181'
certbot_auto_renew: yes
certbot_auto_renew_user: "{{ ansible_user }}"
certbot_auto_renew_hour: 5
certbot_auto_renew_minute: 19
certbot_install_from_source: yes
