---
- name: Ensure Postgresql packages are the latest.
  apt: name={{ item }} state=latest
  with_items:
    - gdal-bin
    - proj-bin
    - postgresql-server-dev-all

- name: Ensure Postgresql is configured to listen all interfaces.
  lineinfile:
    dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: "^listen_addresses = "
    line: "listen_addresses = '*'"
  notify:
    - restart postgresql

- name: Ensure Postgresql is configured to allow remote Django app login.
  lineinfile:
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    line: "host all all {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}/32 trust"
  with_items: "{{ groups['webservers'] }}"
  notify:
    - restart postgresql
