---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Ensure hostname is set.
      hostname: name={{ inventory_hostname }}

    - name: Ensure hosts are set.
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ item.key }}"
        line: "{{ item.value }} {{ item.key }}"
      with_dict: "{{ private_ips }}"

    - name: Ensure OS packages are the latest.
      apt: upgrade=yes update_cache=yes cache_valid_time=86400

    - name: Ensure locales are generated.
      command: locale-gen zh_TW.UTF-8
