---
- hosts: all
  tasks:
    - name: Collect facts
      debug:

#- hosts: dbservers
  #become: yes
  #vars_files:
    #- vars/secret.yml
  #vars:
    #postgresql_version: 9.1
    #postgresql_encoding: 'UTF-8'
    #postgresql_ext_install_postgis: yes
  #roles:
    #- ANXS.postgresql
    #- localwiki-postgresql

- hosts: cacheservers
  become: yes
  vars_files:
    - vars/secret.yml
  vars:
    memcached_listen_ip: 0.0.0.0
    redis_bind_interface: 0.0.0.0
    firewall_allowed_tcp_ports:
      - "22"
    firewall_allowed_udp_ports: []
  roles:
    - geerlingguy.firewall
    - geerlingguy.memcached
    - geerlingguy.redis
    - geerlingguy.java
    - geerlingguy.solr
  tasks:
    - name: Ensure webservers has access to cacheservers.
      lineinfile:
        dest=/etc/firewall.bash
        insertafter='^# Additional custom rules.'
        line='iptables -A INPUT -s {{ hostvars[item].ansible_eth0.ipv4.address }} -j ACCEPT'
      with_items: "{{ groups['webservers'] }}"

- hosts: webservers
  become: yes
  vars_files:
    - vars/secret.yml
  roles:
    - geerlingguy.apache
    - geerlingguy.varnish
