---
- hosts: cacheservers
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secret.yml
  vars:
    memcached_listen_ip: 0.0.0.0
    redis_bind_interface: 0.0.0.0
    firewall_allowed_tcp_ports:
      - "22"
    firewall_allowed_udp_ports: []
  roles:
    - geerlingguy.firewall
    - geerlingguy.memcached
    - geerlingguy.redis
    - geerlingguy.solr
  tasks:
    - name: Ensure webservers has access to cacheservers.
      lineinfile:
        dest=/etc/firewall.bash
        insertafter='^# Additional custom rules.'
        line='iptables -A INPUT -s {{ hostvars[item].ansible_eth0.ipv4.address }} -j ACCEPT'
      with_items: "{{ groups['webservers'] }}"

