---
- hosts: all
  tasks:
    - name: Collect facts.
      debug:

- include: provision-dbservers.yml

- include: provision-cacheservers.yml

- include: provision-webservers.yml

- include: provision-loadbalancers.yml
