---
- hosts: dbservers
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secret.yml
  vars:
    postgresql_version: 9.1
    postgresql_encoding: 'UTF-8'
    postgresql_ext_install_postgis: yes
    postgresql_pg_hba_trust_hosts: "{{ groups['webservers'] }}"
  roles:
    - ANXS.postgresql
  tasks:
    # XXX might not need this anymore...
    - name: Ensure PostGIS packages are the latest.
      apt: name={{ item }} state=latest
      with_items:
        - gdal-bin
        #- proj
        - postgresql-server-dev-all
        - postgresql-9.1-postgis-2.1
