---
- include: secret.yml

#- hosts: dbservers
  #become: yes
  #roles:
    #- ANXS.postgresql
    #- localwiki-postgresql

- hosts: cacheservers
  become: yes
  vars:
    memcached_listen_ip: 0.0.0.0
    redis_bind_interface: 0.0.0.0
    firewall_allowed_tcp_ports:
      - "22"
    firewall_allowed_udp_ports: []
  roles:
    - geerlingguy.firewall
    - geerlingguy.memcached
    - geerlingguy.redis
  tasks:
    - name: Ensure webservers has access to cacheservers.
      lineinfile:
        dest=/etc/firewall.bash
        insertafter='^# Additional custom rules.'
        line='iptables -A INPUT -s {{ hostvars[item].ansible_eth0.ipv4.address }} -j ACCEPT'
      with_items: "{{ groups['webservers'] }}"

- hosts: webservers
  become: yes
  vars:
    varnish_version: "3.0.5-2"
  roles:
    - geerlingguy.apache
    - geerlingguy.varnish
