---
- hosts: webservers
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secret.yml
  roles:
    - geerlingguy.apache

- hosts: webservers
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secret.yml
  tasks:
    - name: Ensure webapp group exists.
      group: name={{ localwiki_group }}

    - name: Ensure webapp user exists.
      user: name={{ localwiki_user }} group={{ localwiki_group }}

    - name: Ensure webapp directory exists.
      file: dest={{ localwiki_webapp_dir }} owner={{ localwiki_user }} group={{ localwiki_group }} state=directory

    - name: Ensure Ubuntu APT key exists
      apt_key: keyserver=keyserver.ubuntu.com id=
      with_items:
        - 2EA8F35793D8809A
        - 314DF160

    - name: Ensure APT libraries exist.
      apt: name={{ item }}
      with_items:
        - python-apt

    - name: Ensure APT repository exists
      apt_repository: repo={{ item }}
      with_items:
        - ppa:ubuntugis/ubuntugis-unstable

    - name: Ensure OS package dependencies are the latest.
      apt: name={{ item }}
      with_items:
        - python-virtualenv
        - python-dev
        - python-setuptools
        - python-psycopg2
        - python-lxml
        - python-imaging
        - python-pip
        - python-software-properties
        - git
        #- unattended-upgrades
        - binutils
        - libproj-dev
        - gdal-bin
        - libgeos-3.4.2
        - yui-compressor
