---
# Gather facts
- include: os.yml

- include: secret.yml

- hosts: dbservers
  become: yes
  vars:
    postgresql_version: 9.1
    postgresql_encoding: 'UTF-8'
    postgresql_databases:
      - name: lowiki
        owner: lowiki
    postgresql_user_privileges:
      - name: lowiki
        db: lowiki
        priv: "ALL"
        role_attr_flags: "CREATEDB"
    postgresql_database_extensions:
      - db: lowiki
        extensions:
          - postgis
    postgresql_ext_install_postgis: yes
  roles:
    - ANXS.postgresql
    - localwiki-postgresql
